#Chapter 1
#**Data Manipulation with Pandas.**

#PANDAS

**Data Manipulation using Pandas**

###**1**. Series

In [4]:
import pandas as pd
marks = [2,4,6,8,10]
ds= pd.Series(marks)
print(ds)
print(type(ds))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["ujjwal", "ram", "shyam", "honey", "siya"])
print(ds)

ujjwal     2
ram        4
shyam      6
honey      8
siya      10
dtype: int64

In [6]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["ujjwal", "ram", "shyam", "honey", "siya"])
print(ds)

ujjwal     2
ram        4
shyam      6
honey      8
siya      10
dtype: int64

In [7]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["ujjwal", "ram", "shyam", "honey", "siya"],dtype= "float",name="marksheet record")
print(ds)

ujjwal     2.0
ram        4.0
shyam      6.0
honey      8.0
siya      10.0
Name: marksheet record, dtype: float64

1. Common operations
s.sum() \
s.mean() \
s.max() \
s.min()

In [8]:
print("sum no in series:",ds.sum())
print("mean no in series:",ds.mean())
print("max no in series:",ds.max())
print("min no in series:",ds.min())

sum no in series: 30.0
mean no in series: 6.0
max no in series: 10.0
min no in series: 2.0

1.2 Indexing and Slicing

In [9]:
print(f"access element by int{ds[0]}")
print(f"access element by int{ds[1]}")
print(f"access element by int{ds[2]}")
print(f"access element by int{ds[3]}")

access element by int2.0
access element by int4.0
access element by int6.0
access element by int8.0

/tmp/ipykernel_1419/1218810201.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"access element by int{ds[0]}")
/tmp/ipykernel_1419/1218810201.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"access element by int{ds[1]}")
/tmp/ipykernel_1419/1218810201.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"access element by int{ds[2]}")
/tmp/ipykernel_1419/1218810201.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"access element by int{ds[3]}")

In [10]:
print("access element by var",ds["A"])
print("access element by var",ds["B"])
print("access element by var",ds["C"])

KeyError: 'A'

In [11]:
print(f"Slicing in series:\n{ds[0:3]}")

Slicing in series:
ujjwal    2.0
ram       4.0
shyam     6.0
Name: marksheet record, dtype: float64

1.3 Vectorization Function

In [12]:
print(ds*3)
print(ds+2)

ujjwal     6.0
ram       12.0
shyam     18.0
honey     24.0
siya      30.0
Name: marksheet record, dtype: float64
ujjwal     4.0
ram        6.0
shyam      8.0
honey     10.0
siya      12.0
Name: marksheet record, dtype: float64

In [13]:
info = {
    "name": "ujjwal",
    "age": 20,
    "marks": [20,30,40,21]
}
ds1 = pd.Series(info)
print(ds1)
ds1

name               ujjwal
age                    20
marks    [20, 30, 40, 21]
dtype: object

name               ujjwal
age                    20
marks    [20, 30, 40, 21]
dtype: object

In [14]:
ds1["name"]

'ujjwal'

Check error if we have only one row or column

In [15]:
num = pd.Series(5) #max 1 column and can be multiple rows
print(num)

0    5
dtype: int64

In [16]:
num = pd.Series(5,index=[1,2,3,4])
print(num)

1    5
2    5
3    5
4    5
dtype: int64

In [17]:
num1 = pd.Series(5,index=[1,2,3,4])
num2 = pd.Series(10,index=[1,2,3,4])
print(num1+num2)

1    15
2    15
3    15
4    15
dtype: int64

In [18]:
num1 = pd.Series(5,index=[1,2,3,4,5])
num2 = pd.Series(10,index=[0,5,10,15,20])
print(num1+num2)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5     15.0
10     NaN
15     NaN
20     NaN
dtype: float64

In [19]:
num1 = pd.Series(5,index=[1,2,3,4,5])
num2 = pd.Series(10,index=["a","b","c","d","e"])
print(num1+num2)

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

###**1**. Series

In [20]:
import pandas as pd
marks = [2,4,6,8,10]
ds= pd.Series(marks)
print(ds)
print(type(ds))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [21]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["ujjwal", "jatin", "ram", "shyam", "siya"])
print(ds)

ujjwal     2
jatin      4
ram        6
shyam      8
siya      10
dtype: int64

In [22]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["ujjwal", "jatin", "ram", "shyam", "siya"])
print(ds)

ujjwal     2
jatin      4
ram        6
shyam      8
siya      10
dtype: int64

In [23]:
import pandas as pd
marks = [2,4,6,8,10]       #Customized index
ds= pd.Series(marks, index=["ujjwal", "jatin", "ram", "shyam", "siya"],dtype= "float",name="marksheet record")
print(ds)

ujjwal     2.0
jatin      4.0
ram        6.0
shyam      8.0
siya      10.0
Name: marksheet record, dtype: float64

**1.1 Common Operations**

1.   s.sum()
2.   s.mean()
3.   s.max()
4.   s.min()

In [24]:
print(ds.sum())
print(f"min num in series:", ds.min())
print(f"min num in series:", ds.max())
print(f"min num in series:", ds.mean())

30.0
min num in series: 2.0
min num in series: 10.0
min num in series: 6.0

**1.3  Indexing and Slicing**

In [25]:
print(f"Access element by Integer number", {ds[0]})

Access element by Integer number {np.float64(2.0)}

/tmp/ipykernel_1419/2462878888.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Access element by Integer number", {ds[0]})

In [26]:
print(f"Access element by Variable", ds[2])

Access element by Variable 6.0

/tmp/ipykernel_1419/3048248043.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Access element by Variable", ds[2])

In [27]:
print("slicing in series", ds[0:3])

slicing in series ujjwal    2.0
jatin     4.0
ram       6.0
Name: marksheet record, dtype: float64

## **1.3 Vectorization Function**

In [28]:
print(ds*3)
print(ds+3)
print(ds-3)
print(ds/3)
print(ds**3)
print(ds%3)

ujjwal     6.0
jatin     12.0
ram       18.0
shyam     24.0
siya      30.0
Name: marksheet record, dtype: float64
ujjwal     5.0
jatin      7.0
ram        9.0
shyam     11.0
siya      13.0
Name: marksheet record, dtype: float64
ujjwal   -1.0
jatin     1.0
ram       3.0
shyam     5.0
siya      7.0
Name: marksheet record, dtype: float64
ujjwal    0.666667
jatin     1.333333
ram       2.000000
shyam     2.666667
siya      3.333333
Name: marksheet record, dtype: float64
ujjwal       8.0
jatin       64.0
ram        216.0
shyam      512.0
siya      1000.0
Name: marksheet record, dtype: float64
ujjwal    2.0
jatin     1.0
ram       0.0
shyam     2.0
siya      1.0
Name: marksheet record, dtype: float64

In [29]:
info= {"name": "chetan", "marks":[20,30,28,21]}     #dictionary in series
ds1= pd.Series(info)
print(ds1)

name               chetan
marks    [20, 30, 28, 21]
dtype: object

In [30]:
info= {"name": "chetan", "marks":[20,30,28,21]}
ds1= pd.Series(info)
print(ds1)
ds1

name               chetan
marks    [20, 30, 28, 21]
dtype: object

name               chetan
marks    [20, 30, 28, 21]
dtype: object

In [31]:
ds1["name"]     #working as indexing

'chetan'

**Minimum Series**

In [32]:
num= pd.Series(5)     #Maximum 1 column and 1 row
print(num)

0    5
dtype: int64

In [33]:
num= pd.Series(5, index=[1,2,3,4,5])     #Maximum 1 column and multiple rows
print(num)

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [34]:
num1= pd.Series(5, index=[1,2,3,4,5])     #same indexing se hojayega
num2= pd.Series(10, index=[1,2,3,4,5])
print(num1+num2)

1    15
2    15
3    15
4    15
5    15
dtype: int64

In [35]:
num1= pd.Series(5, index=[1,2,3,4,5])
num2= pd.Series(10, index=[0,5,10,15,25])     #different index se nahi hoga
print(num1+num2)                              #NaN stands for Not a Number

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5     15.0
10     NaN
15     NaN
25     NaN
dtype: float64

In [36]:
num1= pd.Series(5, index=[1,2,3,4,5])
num2= pd.Series(10, index=["a","b","c","d","e"])
print(num1+num2)

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

**2.0 Main Data Structures**

**2.1 DataFrame**

In [37]:
import pandas as pd
Students={
    "Names":["ujjwal", "ram","shyam"],
    "Roll_num": [100,101,102],
    "Marks":[80,86,88]
        }
DF = pd.DataFrame(Students)
print(DF)

    Names  Roll_num  Marks
0  ujjwal       100     80
1     ram       101     86
2   shyam       102     88

In [38]:
import pandas as pd
Students={
    "Names":["ujjwal", "ram","shyam"],
    "Roll_num": [100,102],
    "Marks":[80,86,88]
}
DF = pd.DataFrame(Students)
print(DF)

ValueError: All arrays must be of the same length

**Creating a Dataframe with list*

In [39]:
Studentsinfo=[['A','B','C'], [20,40,60]]
DF= pd.DataFrame(Studentsinfo)
print(DF)     #using here print(DF)

    0   1   2
0   A   B   C
1  20  40  60

In [40]:
Studentsinfo=[['A','B','C'], [20,40,60]]
DF= pd.DataFrame(Studentsinfo)
DF      #Only using DF

    0   1   2
0   A   B   C
1  20  40  60

***Multiple Series to make Dataframe***

In [41]:
Sr={
    "Name": pd.Series(['A','B','C','D','E']),
    "Marks": pd.Series([10,20,30,40,50])
}
DF= pd.DataFrame(Sr)
print(DF)

  Name  Marks
0    A     10
1    B     20
2    C     30
3    D     40
4    E     50

**2.2 Performing Arithmetic Operations in DF**

In [42]:
var= pd.DataFrame({'A':[1,2,3,4,5], 'B':[6,7,8,9,10]})
var["C"]= var["A"]+var['B']
var["C"]= var["A"]-var['B']
var["C"]= var["A"]*var['B']
var["C"]= var["A"]/var['B']
var["C"]= var["A"]%var['B']

var

   A   B  C
0  1   6  1
1  2   7  2
2  3   8  3
3  4   9  4
4  5  10  5

**2.3 Filtering in DF**

In [43]:
var= pd.DataFrame({'A':[1,2,3,4,5], 'B':[6,7,8,9,10]})
var["C"]= var["A"]+var['B']
var["pyhton"]=var["C"]>10    #Filtering
var

   A   B   C  pyhton
0  1   6   7   False
1  2   7   9   False
2  3   8  11    True
3  4   9  13    True
4  5  10  15    True

**2.4 Handling Missing Values**

In [44]:
import numpy as np
import pandas as pd
Sr={
    "Name": pd.Series(['ujjwal','shyam',np.nan,'bunny','honey']),
    "Roll_num": pd.Series([10,20,30,40,50]),
    "Marks": pd.Series([10,20,np.nan,40,50]),
    "Subject":pd.Series(["Hindi","Sans","Maths",np.nan,np.nan]),
    "City":pd.Series(["Meerut","Noida","Delhi",np.nan,"Gurgaon"])
}
DF= pd.DataFrame(Sr)
print(DF)

     Name  Roll_num  Marks Subject     City
0  ujjwal        10   10.0   Hindi   Meerut
1   shyam        20   20.0    Sans    Noida
2     NaN        30    NaN   Maths    Delhi
3   bunny        40   40.0     NaN      NaN
4   honey        50   50.0     NaN  Gurgaon

In [45]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      4 non-null      object
 1   Roll_num  5 non-null      int64
 2   Marks     4 non-null      float64
 3   Subject   3 non-null      object
 4   City      4 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [46]:
DF.isnull()

    Name  Roll_num  Marks  Subject   City
0  False     False  False    False  False
1  False     False  False    False  False
2   True     False   True    False  False
3  False     False  False     True   True
4  False     False  False     True  False

In [47]:
DF.isnull().sum()

Name        1
Roll_num    0
Marks       1
Subject     2
City        1
dtype: int64

In [48]:
print(DF.isnull().sum().sum())

5

In [49]:
#remove null values
DF.dropna()

     Name  Roll_num  Marks Subject    City
0  ujjwal        10   10.0   Hindi  Meerut
1   shyam        20   20.0    Sans   Noida

In [50]:
DF.dropna(subset=["Marks"])

     Name  Roll_num  Marks Subject     City
0  ujjwal        10   10.0   Hindi   Meerut
1   shyam        20   20.0    Sans    Noida
3   bunny        40   40.0     NaN      NaN
4   honey        50   50.0     NaN  Gurgaon

In [51]:
DF["Marks"]=DF["Marks"].fillna(0)
DF

     Name  Roll_num  Marks Subject     City
0  ujjwal        10   10.0   Hindi   Meerut
1   shyam        20   20.0    Sans    Noida
2     NaN        30    0.0   Maths    Delhi
3   bunny        40   40.0     NaN      NaN
4   honey        50   50.0     NaN  Gurgaon

In [52]:
DF["Marks"] = DF["Marks"].fillna(DF["Marks"].max())
DF

     Name  Roll_num  Marks Subject     City
0  ujjwal        10   10.0   Hindi   Meerut
1   shyam        20   20.0    Sans    Noida
2     NaN        30    0.0   Maths    Delhi
3   bunny        40   40.0     NaN      NaN
4   honey        50   50.0     NaN  Gurgaon

In [53]:
DF["Name"].fillna("Khushi")

0    ujjwal
1     shyam
2    Khushi
3     bunny
4     honey
Name: Name, dtype: object