#Data Cleaning and Manipulation

In [2]:
#Importing files
from google.colab import files
upload = files.upload()

Saving messy_clinic.csv to messy_clinic.csv

In [3]:
#Importing libraries
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("messy_clinic.csv")    #Read csv file

In [6]:
df.head()    #First 5 rows

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1

In [7]:
df.tail()   #last 5 rows

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
995,1082,Thomas Roman,64,Female,"September 14, 25",2024/07/15,Robert Bass,General,Rs200.43,Yes
996,1008,Jack Cooper,67,F,"April 09, 25","June 20, 24",Christopher Smith,General,Rs244.49,No
997,1022,Christopher Brown,28,1,"February 13, 26",2024/06/13,Kimberly Johnson,Neurology,£154.48,N
998,1088,Michael Sullivan,65,F,2025/07/04,2024/04/15,Anthony Mccoy,Neurology,$434.95,0
999,1003,Perry Crawford,79,Male,05-Nov-2025,2024/07/22,Marvin Hicks,Cardiology,€102.23,Y

In [13]:
#Study about data like shape,head,info and more details under(describe)

print(df.shape)
print(df.head())
print(df.info())
print(df.describe(include="all"))

(1000, 10)
   patient_id       patient_name  age  gender appointment_date   booking_date  \
0        1080     Tammy Williams   76  female       2026/02/26     2024/12/03
1        1074   Megan Strickland   69       F       05/23/2025    12-Jun-2024
2        1067   Amanda Schroeder   79       M      30-Nov-2025  August 05, 24
3        1072  Anthony Mcpherson   47       F       May 18, 25     09/09/2024
4        1092     Benjamin Brown   45     NaN       2026/03/07     08/17/2024

               doctor   department billing_amount follow_up_required
0  Christopher Graham   Cardiology         £425.8                  1
1       Brandon Lewis  Orthopedics        €344.26                  Y
2      Deanna Edwards    Neurology        €203.34                  Y
3       Karen Parsons      General        Rs85.76                 No
4    Andrea Hernandez      General         $84.44                  1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          1000 non-null   int64
 1   patient_name        1000 non-null   object
 2   age                 1000 non-null   int64
 3   gender              950 non-null    object
 4   appointment_date    1000 non-null   object
 5   booking_date        1000 non-null   object
 6   doctor              1000 non-null   object
 7   department          1000 non-null   object
 8   billing_amount      950 non-null    object
 9   follow_up_required  1000 non-null   object
dtypes: int64(2), object(8)
memory usage: 78.3+ KB
None
         patient_id  patient_name          age gender appointment_date  \
count   1000.000000          1000  1000.000000    950             1000
unique          NaN           988          NaN      8              735
top             NaN  Thomas Smith          NaN      0       2026/02/11
freq            NaN             2          NaN    129                4
mean    1050.521000           NaN    53.750000    NaN              NaN
std       28.888581           NaN    21.137604    NaN              NaN
min     1000.000000           NaN    18.000000    NaN              NaN
25%     1025.000000           NaN    34.000000    NaN              NaN
50%     1051.000000           NaN    55.000000    NaN              NaN
75%     1075.000000           NaN    71.000000    NaN              NaN
max     1100.000000           NaN    90.000000    NaN              NaN

       booking_date           doctor department billing_amount  \
count          1000             1000       1000            950
unique          822              990          4            949
top     21-Jul-2025  Nancy Hernandez  Neurology        €243.78
freq              3                2        273              2
mean            NaN              NaN        NaN            NaN
std             NaN              NaN        NaN            NaN
min             NaN              NaN        NaN            NaN
25%             NaN              NaN        NaN            NaN
50%             NaN              NaN        NaN            NaN
75%             NaN              NaN        NaN            NaN
max             NaN              NaN        NaN            NaN

       follow_up_required
count                1000
unique                  6
top                     0
freq                  185
mean                  NaN
std                   NaN
min                   NaN
25%                   NaN
50%                   NaN
75%                   NaN
max                   NaN

#Step 1 - Check Duplicate Values

In [14]:
df.duplicated().sum()  #Check duplicates

np.int64(0)

In [15]:
df["patient_id"].duplicated().sum()  #also check duplicate patient IDs:

np.int64(899)

#Step 2 - Check repeated patients

In [16]:
df["patient_id"].value_counts().head(10)

patient_id
1074    17
1047    17
1058    17
1015    17
1089    16
1021    16
1088    16
1016    15
1084    15
1036    14
Name: count, dtype: int64

In [79]:
#how repeated patient id look

df[df["patient_id"].duplicated(keep=False)].sort_values("patient_id").head(20)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required,currency
322,1000,Alejandro Lopez,85,Male,2025-06-15,2024-07-03,Brian Bowman,Neurology,€361.32,No,€
160,1000,Christopher Singleton,81,Female,2025-10-26,2025-02-19,Brandy Graves,General,$65.06,Yes,$
741,1000,Angela Rogers,18,Male,2025-08-14,2025-04-10,Dr. Brian Smith,Orthopedics,Rs362.08,No,Rs
857,1001,Dave Summers,25,Female,2026-02-09,2025-01-19,Traci Hopkins,Orthopedics,$217.51,Yes,$
575,1001,Jenny Black,33,Female,2025-11-14,2025-09-06,Jamie Nunez,Neurology,$381.93,No,$
819,1001,Erik Davis,30,Male,2025-05-30,2024-12-05,Amanda White,Neurology,NaN,Yes,nan
579,1001,Jacqueline West,70,Male,2026-01-19,2025-01-17,Steven Walker,General,£148.74,Yes,£
40,1001,Melanie Gibson,50,Male,2025-08-17,2024-09-23,Alison Stanton,Orthopedics,$268.14,Yes,$
775,1001,Haley King,84,Male,2026-02-12,2024-06-21,Erin Carr,Cardiology,€239.93,No,€
47,1001,Michael Allen,64,Female,2025-07-29,2024-06-08,Brian Osborne DVM,Orthopedics,€214.44,No,€
765,1001,Richard Griffin,61,Male,2025-10-24,2025-08-21,Tina Gonzalez,Orthopedics,Rs81.87,Yes,Rs
646,1001,Tiffany Stone,27,Female,2025-08-18,2025-05-23,Henry Kelley,Neurology,€180.76,No,€
388,1001,Robert Hampton,90,Male,2025-11-12,2025-09-04,Kevin Wilkinson,Neurology,£323.18,No,£
399,1001,Brian Bolton,78,Male,2025-08-18,2024-05-26,Natalie Patrick,Neurology,£163.58,No,£
710,1001,Ellen Stevens,35,Male,2025-07-14,2024-07-02,Charles Wells,Orthopedics,£479.79,No,£
482,1002,Lawrence Ford,89,Female,2025-07-09,2025-01-03,Randall Watts,Neurology,€167.8,Yes,€
152,1002,Jeffrey Bates,87,Male,2025-04-08,2024-12-04,Lisa Ho,Cardiology,$401.55,Yes,$
880,1002,Maria Williams,22,Male,2025-08-17,2025-01-05,Brandi Thomas,Orthopedics,£189.17,No,£
28,1002,Cassandra Gardner,42,Male,2025-10-14,2024-11-04,Gregory Kirk,Neurology,Rs342.38,No,Rs
183,1002,Dr. Michele Copeland,35,Male,2025-09-25,2024-05-24,Debra Castillo,Neurology,€187.28,Yes,€

#Step 3 - Checking missing values

In [18]:
df.isnull().sum()

patient_id             0
patient_name           0
age                    0
gender                50
appointment_date       0
booking_date           0
doctor                 0
department             0
billing_amount        50
follow_up_required     0
dtype: int64

In [19]:
(df.isnull().sum() / len(df)) * 100    #for percentaeg of missing values

patient_id            0.0
patient_name          0.0
age                   0.0
gender                5.0
appointment_date      0.0
booking_date          0.0
doctor                0.0
department            0.0
billing_amount        5.0
follow_up_required    0.0
dtype: float64

#Step 4 - check gender column

In [20]:
df["gender"].value_counts(dropna=False)

gender
0         129
1         128
Male      123
Female    120
F         116
female    112
male      112
M         110
NaN        50
Name: count, dtype: int64

In [21]:
df[df["gender"].isnull()].head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
36,1003,Katelyn Smith,19,NaN,"October 16, 25",09/21/2025,Robert Henry,Neurology,$481.44,0
43,1063,Edward Sanders,29,NaN,2025/09/16,"April 29, 25",Steven Bailey,Orthopedics,Rs479.77,0
64,1077,Jennifer Stark,34,NaN,06/29/2025,04-Dec-2024,Jason Williams,Neurology,Rs270.33,N
70,1095,Jessica Heath,86,NaN,2025/06/25,04/24/2024,Sherri Long,Cardiology,€61.37,Yes
84,1093,Craig Nixon,55,NaN,2025/10/12,08/20/2025,William Key,Neurology,£341.19,No
91,1040,Chelsea Burns,62,NaN,"December 29, 25",13-May-2024,Michael Morales,Cardiology,Rs193.6,Yes
102,1088,Sarah Hahn,60,NaN,19-Mar-2026,2024/10/18,Theresa Lee,General,Rs123.03,Yes
108,1018,Monica Horton,53,NaN,11-Oct-2025,"March 30, 24",Kayla Stein,Neurology,$277.21,Yes
125,1053,John Johnson,81,NaN,23-Apr-2025,2024/12/30,Steve Bush,General,$162.94,N

In [80]:
df["gender"].dtype     #how many data types are in gender

dtype('O')

#Step 5 — Check billing_amount

In [24]:
df["billing_amount"].value_counts(dropna=False).head(20)

billing_amount
NaN         50
€243.78      2
$184.11      1
Rs277.5      1
Rs63.99      1
Rs85.56      1
€237.1       1
€250.69      1
$421.57      1
€77.79       1
€156.32      1
$249.74      1
$126.56      1
$143.32      1
£353.8       1
£174.54      1
£217.77      1
Rs277.51     1
£259.19      1
Rs492.92     1
Name: count, dtype: int64

In [25]:
df["billing_amount"].dtype

dtype('O')

In [26]:
df[df["billing_amount"].isnull()].head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
33,1041,Nicole Shaw,20,male,05/07/2025,01/19/2025,Mr. Brian Morton,Neurology,NaN,Y
75,1061,Jessica Smith,66,female,08/20/2025,2025/03/08,Crystal Mack,Neurology,NaN,Yes
97,1052,Keith Becker,60,female,11/07/2025,"August 28, 24",Kristopher Collier,General,NaN,Y
140,1069,Thomas Landry,60,1,"September 03, 25",08/01/2025,Brandon Moore,General,NaN,No
145,1047,John Campbell,67,0,10-Feb-2026,06/21/2024,Tanya Baxter,Orthopedics,NaN,N
159,1038,Lindsay Rodriguez,39,male,23-Oct-2025,07/18/2025,Troy Lynch,Orthopedics,NaN,0
176,1091,David Martinez,80,Male,2025/09/13,07-Jul-2025,Amber Braun,Cardiology,NaN,Y
195,1087,Kimberly Guzman,31,0,11/18/2025,02-Apr-2025,Kristin Reeves,General,NaN,Y
196,1056,Terry Miller,24,F,22-Apr-2025,"March 24, 25",John Lyons,General,NaN,Yes

In [27]:
df["billing_amount"].astype(str).str.extract(r"(^[A-Za-z€£$]+)")[0].value_counts()

0
Rs     252
$      241
€      237
£      220
nan     50
Name: count, dtype: int64

#Step 6 — Check the appointment and booking date columns

In [28]:
df["appointment_date"].value_counts().head(20)

appointment_date
2026/02/11          4
2025/08/13          4
2025/10/30          4
2025/07/04          3
July 29, 25         3
05/29/2025          3
January 10, 26      3
August 17, 25       3
15-Dec-2025         3
11/07/2025          3
31-Oct-2025         3
2025/07/23          3
09-Jan-2026         3
21-Oct-2025         3
2025/05/13          3
September 03, 25    3
21-Sep-2025         3
December 01, 25     3
May 23, 25          3
November 16, 25     3
Name: count, dtype: int64

In [29]:
df["booking_date"].value_counts().head(20)

booking_date
21-Jul-2025      3
2024/07/06       3
2024/06/03       3
09-Dec-2024      3
2025/05/13       3
05/18/2024       3
04/14/2024       3
2024/04/15       3
August 05, 24    3
06-Nov-2024      3
31-Jul-2024      3
05/24/2025       3
13-Feb-2025      3
05-Oct-2024      2
2024/11/04       2
08/31/2025       2
2025/01/07       2
2024/05/09       2
05/31/2025       2
2024/11/14       2
Name: count, dtype: int64

In [30]:
df[["appointment_date", "booking_date"]].dtypes

appointment_date    object
booking_date        object
dtype: object

#Step 6A — Convert appointment_date

In [31]:
df["appointment_date"] = pd.to_datetime(
    df["appointment_date"],
    format="mixed",
    errors="coerce"
)

In [32]:
df["appointment_date"].isnull().sum()

np.int64(0)

In [33]:
df["appointment_date"].dtype

dtype('<M8[ns]')

#Step 6B — Clean booking_date

In [34]:
df["booking_date"] = pd.to_datetime(
    df["booking_date"],
    format="mixed",
    errors="coerce"
)

In [35]:
df["booking_date"].isnull().sum()

np.int64(0)

In [36]:
df["booking_date"].dtype

dtype('<M8[ns]')

#Step 7 — Clean gender

In [37]:
df[df["gender"].isin([0, 1])]["gender"].value_counts()

Series([], Name: count, dtype: int64)

In [38]:
pd.crosstab(df["gender"], df["follow_up_required"])

follow_up_required   0   1   N  No   Y  Yes
gender
0                   25  22  19  22  20   21
1                   20  16  31  19  22   20
F                   28  16  13  19  22   18
Female              22  18  11  21  23   25
M                   18  21  22  14  23   12
Male                19  21  14  19  26   24
female              17  18  21  13  21   22
male                28  11  14  15  20   24

In [39]:
df["gender"].value_counts(dropna=False)

gender
0         129
1         128
Male      123
Female    120
F         116
female    112
male      112
M         110
NaN        50
Name: count, dtype: int64

#Step 7A — Standardize gender

In [42]:
df["gender"] = df["gender"].replace({
    "1": "Male",
    "0": "Female",
    "M": "Male",
    "male": "Male",
    "F": "Female",
    "female": "Female"
})

In [43]:
df["gender"].value_counts(dropna=False)

gender
Female    477
Male      473
NaN        50
Name: count, dtype: int64

#Step 7C — Handle the 50 missing genders

In [44]:
df["gender"] = df["gender"].fillna("Unknown")

In [45]:
df["gender"].value_counts()

gender
Female     477
Male       473
Unknown     50
Name: count, dtype: int64

#Step 8 — Clean

In [46]:
df["follow_up_required"].value_counts(dropna=False)

follow_up_required
0      185
Y      182
Yes    181
N      154
1      151
No     147
Name: count, dtype: int64

In [48]:
#Conbvert error to yes and no
df["follow_up_required"] = df["follow_up_required"].replace({
    "0": "No",
    "Y": "Yes",
    "Yes": "Yes",
    "N": "No",
    "1": "Yes",
    "No": "No"
})

In [49]:
df["follow_up_required"].value_counts(dropna=False)

follow_up_required
Yes    514
No     486
Name: count, dtype: int64

#Step 9 — Clean billing_amount

#9A — Create a currency name and currency value column

In [51]:
df["currency"] = df["billing_amount"].astype(str).str.extract(r"(^[A-Za-z€£$]+)")[0]

In [52]:
df["currency"].value_counts(dropna=False)

currency
Rs     252
$      241
€      237
£      220
nan     50
Name: count, dtype: int64

#9B — Extract the numeric amount

In [53]:
df["billing_numeric"] = (
    df["billing_amount"]
    .astype(str)
    .str.replace(r"[^0-9.]", "", regex=True)
)

df["billing_numeric"] = pd.to_numeric(
    df["billing_numeric"],
    errors="coerce"
)

In [54]:
df[["billing_amount", "currency", "billing_numeric"]].head(10)

  billing_amount currency  billing_numeric
0         £425.8        £           425.80
1        €344.26        €           344.26
2        €203.34        €           203.34
3        Rs85.76       Rs            85.76
4         $84.44        $            84.44
5            NaN      nan              NaN
6          €99.0        €            99.00
7       Rs374.63       Rs           374.63
8        $452.37        $           452.37
9        €494.97        €           494.97

#Step 10 — Check missing billing_numeric

In [55]:
df["billing_numeric"].isnull().sum()

np.int64(50)

In [56]:
df["billing_numeric"].fillna(...)

0       425.8
1      344.26
2      203.34
3       85.76
4       84.44
        ...
995    200.43
996    244.49
997    154.48
998    434.95
999    102.23
Name: billing_numeric, Length: 1000, dtype: object

#Step 10A — Check the numeric billing statistics

In [57]:
df["billing_numeric"].describe()

count    950.000000
mean     276.116874
std      130.124170
min       51.380000
25%      162.955000
50%      269.840000
75%      389.227500
max      499.750000
Name: billing_numeric, dtype: float64

In [58]:
df.groupby("currency")["billing_numeric"].agg(["count", "mean", "min", "max"])

          count        mean    min     max
currency
$           241  270.427967  51.72  498.84
Rs          252  285.299563  55.55  499.72
nan           0         NaN    NaN     NaN
£           220  274.913364  51.93  499.67
€           237  273.255105  51.38  499.75

#Step 11 — Check age for invalid values

In [59]:
df["age"].describe()

count    1000.000000
mean       53.750000
std        21.137604
min        18.000000
25%        34.000000
50%        55.000000
75%        71.000000
max        90.000000
Name: age, dtype: float64

In [60]:
df["age"].sort_values().unique()

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

#Step 12 — Check text columns

In [61]:
df[["patient_name", "doctor", "department"]].nunique()

patient_name    988
doctor          990
department        4
dtype: int64

In [62]:
print(df["department"].value_counts())

department
Neurology      273
Orthopedics    262
Cardiology     234
General        231
Name: count, dtype: int64

In [63]:
print(df["doctor"].value_counts().head(20))

doctor
Nancy Hernandez      2
Nancy Wilson         2
Wesley Johnson       2
Kristen Lopez        2
James Aguilar        2
Christopher Smith    2
Benjamin Brown       2
Jennifer Adams       2
Jennifer Carroll     2
Michael Wright       2
David Riley          1
Erin Chandler        1
Eric Kennedy         1
Robin Hebert         1
Zachary Hamilton     1
Robin Medina         1
Kenneth Johnson      1
Justin Smith         1
Misty Higgins        1
Mr. Ricky Le         1
Name: count, dtype: int64

#Step 13 — Check spaces in text columns

In [64]:
for col in ["patient_name", "doctor", "department", "follow_up_required"]:
    print(f"\n{col}:")
    print(df[col].astype(str).str.strip().value_counts().head(15))

patient_name:
patient_name
Thomas Smith          2
Regina Wilson         2
Christopher Brown     2
Daniel White          2
Kyle Jones            2
Brian Davis           2
Jennifer Schwartz     2
Katelyn Miller        2
Christopher Lopez     2
Erika Davis           2
Michael Sullivan      2
Pamela Davis          2
Jeremy Coleman        1
Ryan Rodriguez        1
Richard Richardson    1
Name: count, dtype: int64

doctor:
doctor
Nancy Hernandez      2
Nancy Wilson         2
Wesley Johnson       2
Kristen Lopez        2
James Aguilar        2
Christopher Smith    2
Benjamin Brown       2
Jennifer Adams       2
Jennifer Carroll     2
Michael Wright       2
David Riley          1
Erin Chandler        1
Eric Kennedy         1
Robin Hebert         1
Zachary Hamilton     1
Name: count, dtype: int64

department:
department
Neurology      273
Orthopedics    262
Cardiology     234
General        231
Name: count, dtype: int64

follow_up_required:
follow_up_required
Yes    514
No     486
Name: count, dtype: int64

In [65]:
for col in ["patient_name", "doctor", "department", "follow_up_required"]:
    spaces = df[col].astype(str).ne(df[col].astype(str).str.strip()).sum()
    print(col, ":", spaces)

patient_name : 0
doctor : 0
department : 0
follow_up_required : 0

#Step 14 — Again Check the complete dataset

1. Missing values

In [66]:
df.isnull().sum()

patient_id             0
patient_name           0
age                    0
gender                 0
appointment_date       0
booking_date           0
doctor                 0
department             0
billing_amount        50
follow_up_required     0
currency               0
billing_numeric       50
dtype: int64

2. Data types

In [67]:
df.dtypes

patient_id                     int64
patient_name                  object
age                            int64
gender                        object
appointment_date      datetime64[ns]
booking_date          datetime64[ns]
doctor                        object
department                    object
billing_amount                object
follow_up_required            object
currency                      object
billing_numeric              float64
dtype: object

3. Unique values in categorical columns

In [68]:
for col in ["gender", "department", "follow_up_required", "currency"]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 gender
gender
Female     477
Male       473
Unknown     50
Name: count, dtype: int64

 department
department
Neurology      273
Orthopedics    262
Cardiology     234
General        231
Name: count, dtype: int64

 follow_up_required
follow_up_required
Yes    514
No     486
Name: count, dtype: int64

 currency
currency
Rs     252
$      241
€      237
£      220
nan     50
Name: count, dtype: int64

4. Check duplicate rows again

In [69]:
df.duplicated().sum()

np.int64(0)

5. Check date range

In [70]:
print("Appointment:", df["appointment_date"].min(), "to", df["appointment_date"].max())
print("Booking:", df["booking_date"].min(), "to", df["booking_date"].max())

Appointment: 2025-03-26 00:00:00 to 2026-03-26 00:00:00
Booking: 2024-03-26 00:00:00 to 2026-03-07 00:00:00

6. Check whether booking dates occur after appointments

In [71]:
(df["booking_date"] > df["appointment_date"]).sum()

np.int64(0)

#Step 15 — Check booking date vs appointment date

In [72]:
(df["booking_date"] > df["appointment_date"]).sum()

np.int64(0)

In [73]:
df[df["booking_date"] > df["appointment_date"]][
    ["patient_id", "appointment_date", "booking_date"]
].head(10)

Empty DataFrame
Columns: [patient_id, appointment_date, booking_date]
Index: []

#Step 16 — Final check for missing values

In [74]:
df.isnull().sum()

patient_id             0
patient_name           0
age                    0
gender                 0
appointment_date       0
booking_date           0
doctor                 0
department             0
billing_amount        50
follow_up_required     0
currency               0
billing_numeric       50
dtype: int64

#Step 17 — Remove the temporary column

In [75]:
df.drop(columns=["billing_numeric"], inplace=True)

#Step 18 — Final duplicate check

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          1000 non-null   int64
 1   patient_name        1000 non-null   object
 2   age                 1000 non-null   int64
 3   gender              1000 non-null   object
 4   appointment_date    1000 non-null   datetime64[ns]
 5   booking_date        1000 non-null   datetime64[ns]
 6   doctor              1000 non-null   object
 7   department          1000 non-null   object
 8   billing_amount      950 non-null    object
 9   follow_up_required  1000 non-null   object
 10  currency            1000 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 86.1+ KB

#Step 19 — Save the cleaned dataset

In [81]:
df.to_csv("cleaned_messy_clinic.csv", index=False)

In [82]:
import os

print(os.path.exists("cleaned_messy_clinic.csv"))

True

In [83]:

df2 = pd.read_csv("cleaned_messy_clinic.csv")

In [84]:
df2

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required,currency
0,1080,Tammy Williams,76,Female,2026-02-26,2024-12-03,Christopher Graham,Cardiology,£425.8,Yes,£
1,1074,Megan Strickland,69,Female,2025-05-23,2024-06-12,Brandon Lewis,Orthopedics,€344.26,Yes,€
2,1067,Amanda Schroeder,79,Male,2025-11-30,2024-08-05,Deanna Edwards,Neurology,€203.34,Yes,€
3,1072,Anthony Mcpherson,47,Female,2025-05-18,2024-09-09,Karen Parsons,General,Rs85.76,No,Rs
4,1092,Benjamin Brown,45,Unknown,2026-03-07,2024-08-17,Andrea Hernandez,General,$84.44,Yes,$
...,...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,Female,2025-09-14,2024-07-15,Robert Bass,General,Rs200.43,Yes,Rs
996,1008,Jack Cooper,67,Female,2025-04-09,2024-06-20,Christopher Smith,General,Rs244.49,No,Rs
997,1022,Christopher Brown,28,Male,2026-02-13,2024-06-13,Kimberly Johnson,Neurology,£154.48,No,£
998,1088,Michael Sullivan,65,Female,2025-07-04,2024-04-15,Anthony Mccoy,Neurology,$434.95,No,$
999,1003,Perry Crawford,79,Male,2025-11-05,2024-07-22,Marvin Hicks,Cardiology,€102.23,Yes,€